# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170714_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
        migrations.AddField(
            model_name='location',
            name='place_id',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
